onc-healthit/lantern-back-end

- .github/PULL_REQUEST_TEMPLATE.md
JIRA ticket: https://oncprojectracking.healthit.gov/support/browse/LANTERN-3
> added PR checklist.

- README.md
Add documentation about configuring postgres with prometheus.
----
**Submitter:**
- The JIRA ticket for this PR is:  https://oncprojectracking.healthit.gov/support/browse/LANTERN-49
https://oncprojectracking.healthit.gov/support/browse/LANTERN-32
**Primary Reviewer:** @edeyoung 
- Edge …
> Add documentation about configuring postgres

- .gitignore
- README.md
- endpoints/fetcher/fetcher.go
- endpoints/fetcher/fetcher_test.go
- endpoints/main.go
- endpoints/querier/querier.go
- endpoints/querier/querier_test.go
- fhir/parser.go
- fhir/parser_test.go
Add logging to backend code using logrus. NOTE: Convention is to have all logging performed in main application
**Submitter:**
- The JIRA ticket for this PR is:  https://oncprojectracking.healthit.gov/support/browse/LANTERN-25
**Primary Reviewer:** @edeyoung 
- Edge cases have been …
> Add logging using logrus

- NOTICE.md
- README.md
adds license information to README and a notice file with mitre's government contract information.
----
**Submitter:**
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-65
@mayerm94  …
> adds license and notice

- README.md
- docker-compose.yml
**Submitter:**
- The JIRA ticket for this PR is:  https://oncprojectracking.healthit.gov/support/browse/LANTERN-80
- vendor/ directories have been updated
- New dependencies have been added
- Local dependencies have been updated …
> Add lantern-mq to docker-compose

- docker-compose.test.yml
- endpoints/README.md
- endpoints/main.go
- endpoints/vendor/github.com/onc-healthit/lantern-back-end/endpoints/README.md
- endpoints/vendor/github.com/onc-healthit/lantern-back-end/endpoints/main.go
- endpoints/vendor/vendor.json
- prometheus.test.yml
- prometheus.yml
Update timing intervals to match what is running on ec2
**Submitter:**
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-104
- vendor/ directories have been updated
- New dependencies have been added
- Local dependencies have been updated
**Primary Reviewer:** @edeyoung 
- Code has been run locally and the basic functionality …
> Update query intervals

- docker-compose.override.yml
- docker-compose.yml
**Note**: This PR is NOT dependent on https://github.com/onc-healthit/lantern-front-end/pull/11.
- Test by running `docker-compose up` and opening `localhost:8090`.
**Submitter:**
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-93
- vendor/ directories have been updated
- New dependencies have been added
- Local dependencies have been updated
**Primary Reviewer:** @mayerm94 
- Code has been run locally and the basic functionality affected by …
> Docker compose frontend

- capabilityquerier/pkg/capabilityquerier/capabilityquerier.go
- capabilityquerier/vendor/vendor.json
- e2e/vendor/vendor.json
- endpointmanager/pkg/capabilityhandler/capabilityreceiver.go
- endpointmanager/pkg/capabilityhandler/validation.go
- endpointmanager/pkg/endpointmanager/fhirendpoint.go
- endpointmanager/pkg/endpointmanager/postgresql/fhirendpointstore.go
- endpointmanager/vendor/github.com/onc-healthit/lantern-back-end/endpointmanager/pkg/capabilityhandler/capabilityreceiver.go
- endpointmanager/vendor/github.com/onc-healthit/lantern-back-end/endpointmanager/pkg/capabilityhandler/validation.go
- endpointmanager/vendor/github.com/onc-healthit/lantern-back-end/endpointmanager/pkg/endpointmanager/fhirendpoint.go
- endpointmanager/vendor/github.com/onc-healthit/lantern-back-end/endpointmanager/pkg/endpointmanager/postgresql/fhirendpointstore.go
- endpointmanager/vendor/vendor.json
- fhir/vendor/vendor.json
- go.mod
- lanternmq/vendor/vendor.json
- networkstatsquerier/vendor/vendor.json
- scripts/dbsetup.sql
The current validation logic is all in `validation.go` in the capabilityhandler package, since this is a non-permanent solution.
To test:
- `make run`
- At least run: `go run endpointmanager/cmd/capabilityreceiver/main.go`
- You can also run the chplquerier and the endpointpopulator before running the above command, but it's only necessary to run the capabilityreceiver
- Check at least the validation field in the fhir_endpoint database table. I've been using a grafana table to make it easier to see all of the fields in the table, but you can also check by running `docker exec -it pg_prometheus psql -U lantern` in a terminal.
----
**Submitter:**
- This pull request describes why …
> Validation checks

- endpointmanager/pkg/fhirendpointquerier/populatefhirendpoints.go
- endpointmanager/pkg/fhirendpointquerier/populatefhirendpoints_test.go
- endpointmanager/vendor/github.com/onc-healthit/lantern-back-end/endpointmanager/pkg/fhirendpointquerier/populatefhirendpoints.go
- endpointmanager/vendor/github.com/onc-healthit/lantern-back-end/endpointmanager/pkg/fhirendpointquerier/populatefhirendpoints_test.go
- endpointmanager/vendor/vendor.json
This PR is just to replace the organization name and the list source for an endpoint whenever it is updated. Addressing the more complicated issues (saving history, splitting up the current fhir_endpoints table into multiple tables) will be for a future ticket.
This can be tested by running `make populatedb` and verify that the postgres database has the same number of epic endpoints and cerner endpoints according to the `list_source` field as in their respective json files.
------------------
**Submitter:**
- The JIRA ticket for this PR is: …
> Replace endpoints

- Makefile
- endpointmanager/cmd/endpointExporter/main.go
- endpointmanager/cmd/endpointexporter/main.go
- scripts/sql/dbsetup.sql
Add make task 'make csv_export` which will output the contents of the `endpoint_export` database view into a local csv.
**Submitter:**
- The JIRA ticket for this PR is:  https://oncprojectracking.healthit.gov/support/browse/LANTERN-166
- ~The resulting go.mod and go.sum files are the only files in the final commit before the PR is merged~ NA
- Code has been …
> Csv export

- README.md
- docker-compose.yml
See: https://github.com/GoogleCloudPlatform/rabbitmq-docker/blob/master/3/README.md#adding-persistence-1
To test: 
1. Start up lantern, it shouldn't be necessary to run `make clean` and `make populatedb` for this
2. Do not start the capability receiver, but run `lantern-back-end/endpointmanager/cmd/sendendpoints/maini.go`
3. Open up the rabbiitmq management dashboard `http://localhost:15672/` and navigate to the capability-statement queue, you should see that there are a bunch of messages waiting to be pulled off the queue and be processed..... but since we're not running the capability receiver, theres nothing pulling those messages off which means they are existing in the rabbitmq memory.
4. Kill the lanternapp, start it back up and refresh the rabbitmq management page, make sure that …
> Persistent lanternmq

- shinydashboard/lantern/disclaimer.html
- shinydashboard/lantern/ui.R
This PR adds the disclaimer to the bottom of every  page.
**Submitter:**
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-218
- Code is maintainable, …
> Add disclaimer footer to ui.r

- endpointmanager/README.md
This PR defines the CERNER and NPPES endpoint formats the same way that we already do for Epic's format in the endpoint manager README file. I also have added a section to the README that describes how to add a new endpoint list.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern-223 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-223)
- A linter for the language has …
> Define Endpoint Formats in README

- docker-compose.override.yml
- docker-compose.yml
- shinydashboard/Dockerfile
- shinydashboard/lantern/configuration.yml
- shinydashboard/lantern/functions/ui_functions.R
- shinydashboard/lantern/global.R
- shinydashboard/lantern/ui.R
**Submitter:**
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-245 …
> Add development banner

- shinydashboard/lantern/modules/endpointsmodule.R
The endpoint tab on the lantern dashboard now supports horizontal scrolling for the endpoint table.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 241 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-241)
- …
> Add horizontal scroll to endpoints tab table

- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/dashboardmodule.R
- shinydashboard/lantern/server.R
The 'All HTTP Codes Ever Received' visualization on the main dashboard tab of the lantern dashboard now supports filtering by vendor. A drop down menu next to the HTTP response codes table and plot contains a list of all the vendors and can be used to filter the table and plot to only show data for a specific vendor.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 214 JIRA ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-214)
- Code diff has been done and …
> Add Vendor Filtering to 'All HTTP Codes Ever Received' Visualization 

- README.md
- scripts/data_collection_check.sh
This PR adds a script called data_collection_check.sh in the scripts directory. This script checks to make sure that the database has been updated within the query interval. If it has not been updated within the query interval, or if the database is down, an email is sent with an alert of the problem to a configureable email address.
TO TEST:
The README file has been updated with information on setting up the script and running it as a cron job. Set the EMAIL variable equal to your MITRE email or the lantern group email, set the DB_NAME and DB_USER both equal to lantern, and set the query interval equal to any time in seconds, such as 120 for 2 minutes. For testing purposes, consider changing the cron expression you add to the crontab file to execute within a smaller …
> Data Collection Failure System

- README.md
Create lantern-app.service file in /etc/systemd/system directory to automatically start Lantern when system boots up
**Submitter:**
https://oncprojectracking.healthit.gov/support/browse/LANTERN-242
- Code follows style guidance appropriate for the language, including passing …
> Update README with info to start lantern automatically on host machine

- .travis.yml
- Makefile
- README.md
- scripts/lintr.sh
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/functions/ui_functions.R
- shinydashboard/lantern/modules/availabilitymodule.R
- shinydashboard/lantern/modules/dashboardmodule.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/fieldsmodule.R
- shinydashboard/lantern/modules/performancemodule.R
- shinydashboard/lantern/server.R
- shinydashboard/lantern/ui.R
This PR adds a lintr for the R code in the shinydashboard/lantern directory. This lintr runs within a script that exits with a failed status code of 1 if the lintr command returns with any lintr problems. This PR also cleaned up some of the R code according to the lintr tests, and it adds the R lintr to travis. In the make file, the make lint command now includes the R lintr, and now there are two separate make commands, make lint_go and make lint_R, which run the linters for their corresponding language. 
This PR also has updated travis to run all the tests (make test, make test_int, and make test_e2e) in one stage without needing to rebuild the docker image a second time to run make test_e2e, which allows travis to finish running much faster
Pull requests into this …
> Add R Lintr

- capabilityquerier/cmd/main.go
> Remove potential newline from end of useragent

- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/global.R
- shinydashboard/lantern/modules/availabilitymodule.R
This ticket updated the legend title to "HTTP Response Code" and added the url to the tooltip. The other possible updates in the ticket were considered irrelevant since we will likely change this chart in the near future anyways.
To test:
- Go to the shinydashboard (with data loaded in the database) and make sure the first chart in the Availability tab looks as expected.
------
**Submitter:**
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-254
- Code diff …
> Update legend title, move legend, and add url to bar chart tooltip.

- shinydashboard/lantern/global.R
- shinydashboard/lantern/server.R
- shinydashboard/lantern/ui.R
The shiny dashboard URL now contains a search parameter containing information on the tab it is currently on, which looks like <shinyURL>?tab=<current tab>. The tab that 'tab' in the url is equal to should switch to the current tab on every tab switch. Now, when the dashboard is reloaded the shiny dashboard can now check to see what the last tab the dashboard was on in the url search parameter, and then it will redirect the user to that tab when the dashboard reloads. This also allows a url that directs to a specific dashboard tab to be shared and opened in a new window.
**Submitter:**
- The JIRA …
> Shiny Tab Reload

- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/global.R
- shinydashboard/lantern/modules/capabilitymodule.R
Added a visualization for implementation guides to the capability tab on the shiny dashboard. Since all our stored endpoints do not currently have any implementation guides set, a blank table with text explaining that there are no implementation guides is displayed when there are no implmentation guides to be shown, otherwise, a bar chart will be displayed showing the counts of each type of implementation guide.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 257 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-257)
- Tests are …
> Implementation Guide Visualization 

- shinydashboard/lantern/configuration.yml
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/global.R
- shinydashboard/lantern/modules/capabilitymodule.R
- shinydashboard/lantern/modules/fieldsmodule.R
- shinydashboard/lantern/modules/performancemodule.R
- shinydashboard/lantern/modules/valuesmodule.R
- shinydashboard/lantern/server.R
- shinydashboard/lantern/ui.R
This PR adds a new "Values" page that allows the user to see all given values of a specific field in the capability statement. There is also a chart that shows how many endpoints are using the field.
To test:
- Make sure the field values match what is seen when using pgAdmin
- Check the values in the Pie Chart against the table
----------------
**Submitter:**
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-268
- Code diff has been done and checked to ensure …
> Display Capability Statement Values

- db/migration/cmd/main.go
- db/migration/migrations/000005_add_export_fields.down.sql
- db/migration/migrations/000005_add_export_fields.up.sql
- db/sql/dbsetup.sql
- shinydashboard/lantern/fhir_endpoints_fields.csv
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/capabilitymodule.R
- shinydashboard/lantern/modules/endpointsmodule.R
This PR updates the values that are in the `endpoint_export` view and uses them in the endpoint csv based on sponsor needs. A definitions csv file has also been added that explains what each field in the csv is.
To test:
* Check that the "Endpoints" page looks correct and the csv includes all of the required fields
* Make sure the definitions file includes definitions for all of the fields in the endpoint csv
* Try migrating up and down from master to this branch and make sure that works
----------------------
**Submitter:**
- The JIRA ticket for this PR is: …
> Csv export file

- shinydashboard/lantern/modules/endpointsmodule.R
Updated the columns so they have the same names as in the CSV.
-----------------------
**Submitter:**
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-286 …
> Update headers of table columns

- .travis.yml
- Makefile
- shinydashboard/lantern/global.R
**Submitter:**
- The JIRA ticket for this PR is:  https://oncprojectracking.healthit.gov/support/browse/LANTERN-282
- Code follows style guidance appropriate for the language, including …
> Travis speedup

- capabilityquerier/pkg/config/config.go
**Submitter:**
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-285 …
> Connect to test database in capquerier test

- README.md
**Submitter:**
- The JIRA ticket for this PR is:  https://oncprojectracking.healthit.gov/support/browse/LANTERN-295
- Code follows style guidance appropriate for the language, including passing linter checks.
- Code is well commented (which does not mean verbosely commented).
**Merger:**
Prior to merging, ensure that all checks have been …
> 2019->2021

- shinydashboard/lantern/functions/endpoints.R
To test, use the connectathon staging database, see that the IGs in the capability tab are split out as individual IGs.
You will have to hand-modify saved capabilityStatements to see a count > 1.
**Submitter:**
- The JIRA ticket for this PR is:  https://oncprojectracking.healthit.gov/support/browse/LANTERN-304 …
> Display supported IGs individually

- docker-compose.override.yml
- resources/dev_resources/EndpointResourcesList.json
- scripts/populatedb.sh
**Submitter:**
- The JIRA ticket for this PR is:  /etc/lantern/resources/EndpointResourcesList.json 
- Code follows style guidance appropriate for the language, including passing linter …
> Use path that docker-compose mounts the EndpointResourceslist.json file

- endpointmanager/pkg/sendendpoints/sendendpoints.go
The error scanning bug found in the capability querier has been fixed by adding a check in the endpoint manager that makes sure the list of endpoints is not empty before sending a "FINISHED" message to the queue. 
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 297 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-297) …
> FINISHED message scan bug fix

- docker-compose.override.yml
- endpointmanager/cmd/endpointlinker/main.go
**Submitter:**
- The JIRA ticket links to this PR. 
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-306 …
> /go/src/app/resources -> /etc/lantern/resources

- shinydashboard/lantern/configuration.yml
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/global.R
- shinydashboard/lantern/modules/capabilitystatementsizemodule.R
- shinydashboard/lantern/modules/dashboardmodule.R
- shinydashboard/lantern/server.R
- shinydashboard/lantern/ui.R
**Submitter:**
- The JIRA ticket for this PR is:  https://oncprojectracking.healthit.gov/support/browse/LANTERN-308 …
> Add capabilitystatement size tab

- db/migration/migrations/000011_add_response_time_index.down.sql
- db/migration/migrations/000011_add_response_time_index.up.sql
- db/sql/dbsetup.sql
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/performancemodule.R
Instead of only having the average response time for the day, the performance tab response time chart now also displays the maximum and minimum response times for the day. An index has been made on the response_time field of the fhir_endpoints_metadata table to speed up the performance tab, and the SQL query used to output data for the performance tab chart has been fixed to not include response times of 0 for endpoints that did not respond in the average, max, and min calculations.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 310 JIRA …
> Max and Min Response Time Performance Tab

- shinydashboard/lantern/functions/endpoints.R
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 315 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-315) …
> Fix Smart Response Capabilities Query

- endpointmanager/pkg/archivefile/archivefile_integration_test.go
Fixed issue with archive integration test where tests were failing due to Postgres docker container using UTC timezone and local test using EDT timezone.
**Submitter:**
- Edge cases have been checked to ensure …
> fix timezone issue for archive integration test

- shinydashboard/lantern/modules/capabilitymodule.R
- shinydashboard/lantern/server.R
There should now be more explanation on the Capability Page on how the resource filtering works.
------------------
**Submitter:**
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-333 …
> Capability page all resources

- shinydashboard/lantern/server.R
**Submitter:**
- The JIRA ticket links to this PR. 
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-336 …
> Remove extra observes

- shinydashboard/lantern/server.R
- Update the description to include Wes's changes.
- Have read selected in the operation field by default.
- Add note about what not specified means
------------------------------------------
**Submitter:**
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-332
- Code has been run locally and the basic …
> Update capability page

- capabilityquerier/Dockerfile
- capabilityreceiver/Dockerfile
- db/migration/Dockerfile
- e2e/Dockerfile
- endpointmanager/Dockerfile
- endpointmanager/pkg/nppesquerier/populatenpicontacts.go
- shinydashboard/Dockerfile
Changes in this PR
Updated the Dockerfile golang image versions and the shiny Dockerfile RENV version
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 326 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-326)
- Edge cases have been …
> Docker versions update

- shinydashboard/lantern/ui.R
> Remove new tag from shiny values sidebar

- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/fieldsmodule.R
- shinydashboard/lantern/modules/valuesmodule.R
- shinydashboard/lantern/server.R
- There was an endpoint page console error giving a warning for an if statement involving the availability filter, this has been fixed so the error no longer appears
- On the Capability Statement Fields page, if you switched to a filter like “Unknown” for FHIR version and there is no data, this would cause an error to be thrown in the shiny UI for the capability statement and extension plots. This has been fixed so the UI displays an empty chart for both of these when there is no data (instead of an error message)
- On the values page, if you switched to a filter like “Unknown” for FHIR version and there is no data, this would cause an error to be thrown in the shiny UI and in console. This has been fixed so an empty graph is shown instead of the error when there is no …
> Shiny Bug Fixes

- endpointmanager/pkg/endpointmanager/postgresql/historypruningstore.go
- endpointmanager/pkg/historypruning/historypruning.go
- endpointmanager/pkg/historypruning/historypruning_integration_test.go
This PR prunes entries in the validation and validation_results tables that are linked to any fhir_endpoints_info entries that are being pruned.
---------------------
**Submitter:**
- The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-330
- Code has been run locally and the basic functionality affected by the PR …
> History pruning final

- docker-compose.yml
Fixed issue where capabilityreceiver, capabilityquerier, and endpointmanager could not connect to the rabbitMQ queue created by the lanternmq container. Changing the configuration file mounted to the lanternmq container from a .config file to a .conf file fixed the problem of the queue being set up with a default guest configuration. 
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 347 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-347)
- Code diff …
> Fix rabbitmq username/password connection error

- lanternmq/pkg/accessqueue/accessqueue_integration_test.go
The queue integration test that inconsistently breaks was failing due to a timing issue that was not allowing the message to be added to the queue before calling QueueCount to check how many messages were on the queue. Added time.Sleep to ensure the message has time to be inserted on the queue.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 342 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-342)
- Code diff has been done and checked to ensure only …
> Queue test failure fix

- README.md
- scripts/backup.sh
Add backup script to scripts directory (it turns out there weren't any changes that needed to be made to the data_collection_checks script)
To test:
- Run everything and add data to the database
- Add test values to the backup.sh script (see below)
- Run the script: `./backup.sh`
- It should send an email to the specified email address saying that the backup is ready
- The backup file should also be in the backup directory you specified
Test values I used:
- EMAIL=bmathiowetz@mitre.org
- DB_NAME=lantern
- DB_USER=lantern
- BACKUP_DIR=~/Desktop/backups
-------------------------
**Submitter:**
- The JIRA ticket links to …
> Add Backup Script

- shinydashboard/lantern/modules/valuesmodule.R
- shinydashboard/lantern/server.R
…ew field names
Adjusted some of the naming of fields in the field dropdown filter on the Values Tab to be more consistent with the FHIR format, and adjust table to work with these new filter names
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 385 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-385) …
> Change Some Naming of Fields in Dropdown on Values Tab

- shinydashboard/lantern/functions/db_connection.R
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/renv.lock
The endpoint table on the Endpoint Tab of the shiny dashboard can now handle endpoints with multiple versions. The multiple versions are displayed as separate rows merged under one URL row. Since there are no endpoints that support the $versions operator and have more than one version, test by adding some additional endpoints to the fhir_endpoints_info table with the same URL as other endpoints but with different requested versions and capability_fhir_versions.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 356 JIRA …
> Version endpoint page

- shinydashboard/lantern/modules/capabilitymodule.R
- shinydashboard/lantern/modules/fieldsmodule.R
- shinydashboard/renv.lock
Adjusted the Shiny Dashboard Capability tab and Capability Fields tab to have dropdown tables instead of regular tables in order to show the information more compactly. 
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 386 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-386)
- Code has been run locally …
> Capability Dropdown Tables

- shinydashboard/lantern/configuration.yml
- shinydashboard/lantern/modules/capabilitymodule.R
- shinydashboard/lantern/modules/implementationmodule.R
- shinydashboard/lantern/server.R
- shinydashboard/lantern/ui.R
Removed the implementation guide information chart from the capability tab on the Shiny Dashboard and moved to its own Implementation Guides tab
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 388 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-388)
- Code has been run locally and the basic …
> Implementation Guide Information Tab

- shinydashboard/lantern/disclaimer.html
Emily, Jeff, and Brianna are all on the Google group alert-lantern@hitrc.org, changed Lantern email link on dashboard to use that email instead of the old LanternSupport email so the three people currently on the team get those emails.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 396 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-396)
- A linter for the …
> Change Lantern support email to Lantern Google group

- db/migration/migrations/000014_add_versions_operation.up.sql
- db/sql/dbsetup.sql
- shinydashboard/lantern/functions/db_connection.R
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/global.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/securitymodule.R
- shinydashboard/lantern/modules/smartresponsemodule.R
Changed dashboard to show a condensed FHIR version (without any dashes) on most charts and tables, and to do all FHIR version filtering with condensed FHIR version to ensure the endpoint with version 1.0.2-7202 gets grouped with the 1.0.2 endpoints. The full FHIR version is still visible in the table on the Endpoints Tab, in the table on the Values tab when the fhirVersion field filter is selected, and in the tables on the security and smart response tabs. Also, fixed the update_fhir_endpoint_availability_info trigger to specify the columns in the fhir_endpoints_availability table that it is inserting data into
**Submitter:**
- This pull request describes why …
> FHIR Version Shiny Display

- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/global.R
- shinydashboard/lantern/modules/capabilitymodule.R
- shinydashboard/lantern/modules/capabilitystatementsizemodule.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/fieldsmodule.R
- shinydashboard/lantern/modules/implementationmodule.R
- shinydashboard/lantern/modules/locationmodule.R
- shinydashboard/lantern/modules/securitymodule.R
- shinydashboard/lantern/modules/smartresponsemodule.R
- shinydashboard/lantern/modules/validationsmodule.R
- shinydashboard/lantern/modules/valuesmodule.R
- shinydashboard/lantern/server.R
- shinydashboard/renv.lock
Changed the filter FHIR version dropdown from selectInput to pickerInput, which allows for multi-selection of FHIR versions. The filter dropdown is also now grouped by the condensed FHIR version name. 
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 412 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-412)
**Primary …
> General Version Filter

- shinydashboard/lantern/modules/validationsmodule.R
Fixed bug in the validation failure details table that was caused by the new FHIR version filter dropdown
**Submitter:**
- Code accomplishes the tasks …
> Fix Validation Failure Table Bug

- shinydashboard/lantern/disclaimer.html
Changed Lantern Support email from Lantern Alert email back to Lantern Support Group email
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 424 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-424)
- Edge cases …
> Revert email address back to LanternSupport

- README.md
- endpointmanager/cmd/CHPLupdatecheck/main.go
- scripts/chpl_endpoint_list_check.sh
Added a new script to query CHPL's list of endpoint lists to compare it against the list of CHPL endpoints we already have stored in our resources/prod_resources directory. The script grabs the list of endpoint lists from CHPL and compares it to the list of CHPL endpoints we currently have saved to see if any additional URLs have been added to the CHPL endpoint list. If an update is found, the script updates the saved CHPL endpoint list automatically by appending the new entries to the end of the list. An email is then sent alerting of all the updates that took place. Added instructions to the README about how to configure this using cron.
How to Test:
1. …
> Chpl updates cron

- shinydashboard/lantern/modules/validationsmodule.R
Fix the validation information chart so it shows the validation rule FHIR versions when more than one FHIR version selected in FHIR version filter or when "Unknown" FHIR version selected.
**Submitter:**
- Edge …
> Fix validation chart FHIR version

- shinydashboard/lantern/fhir_endpoints_fields.csv
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/endpointsmodule.R
> Important bugs

- shinydashboard/lantern/server.R
- shinydashboard/lantern/ui.R
Added headers to the multiInput filter on the resource page so the side to choose resources and the side where the selected resources are displayed is more clear. Also moved the "How to Use this Page" button on the resource page to the upper right hand side of the page
Also moved the Downloads tab down to bottom part of tab list right before About Lantern tab
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 430 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-430)
- Tests have been run …
> Resource tab adjustments

- endpointmanager/README.md
- endpointmanager/pkg/endpointlinker/endpointlinker.go
- endpointmanager/pkg/endpointlinker/endpointlinker_integration_test.go
- endpointmanager/pkg/endpointmanager/postgresql/fhirendpointstore.go
- endpointmanager/pkg/endpointmanager/postgresql/fhirendpointstore_test.go
- endpointmanager/pkg/testdata/fakeAllowlist.json
Endpoint to NPI organization matches that are added to the allowlist file are now updated in the FHIR endpoint table as well by adding the NPI ID and NPI Organization name. Endpoint to NPI organization matches that are added to the blocklist file are now make sure to remove the information from the FHIR endpoint table as well if it exists. 
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 407 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-407)
- …
> Add Allowlist to FHIR Endpoints Table

- capabilityreceiver/pkg/capabilityhandler/validation/base.go
- capabilityreceiver/pkg/capabilityhandler/validation/validation_test.go
- endpointmanager/pkg/endpointmanager/postgresql/fhirendpointstore_test.go
- endpointmanager/pkg/fhirendpointquerier/populatefhirendpoints.go
- endpointmanager/pkg/fhirendpointquerier/populatefhirendpoints_integration_test.go
- endpointmanager/pkg/nppesquerier/populatenpi_integration_test.go
- endpointmanager/pkg/nppesquerier/populatenpicontacts.go
- shinydashboard/lantern/fhir_endpoints_fields.csv
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/locationmodule.R
Addressed the following bugs:
- _There are 9 Epic Endpoints on the "SMART Response" page that are all the same endpoint but just have different formatting things going on._  While we could not really remove all the URLs with slight typo variations, made it so every endpoint that gets stored in the fhir_endpoints table is preceded by `https://` and ends with a backslash, which will remove any duplicate URL entries that differ either by how the URL scheme is formatted (http, https, HTTP, HTTPS, etc.) or by whether they end with a slash or not, making the URLs a little more consistent. 
- _There are a few epic endpoints that are returning a failure for the …
> Lantern Bugs Fix

- .github/PULL_REQUEST_TEMPLATE.md
> Update template to remove second reviewer

- shinydashboard/lantern/modules/dashboardmodule.R
Fixed overlapping of columns on dashboard tab of shiny dashboard.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 426 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-426) …
> Lantern browser sizing

- Makefile
- README.md
- docker-compose.yml
- scripts/populatedb_prod.sh
- scripts/query-NPPES-resources.sh
Changed way NPPES information was gathered and stored in prod vs dev.
1. make populatedb_prod: Prod now combines gathering the NPPES information, populating the database with the NPPES info and endpoint resource list info, and then deletes the NPPES files using the make populatedb_prod command.
2. make populatedb: Use this command to populate the database with all the endpoint resource information and the stored truncated NPPES files stored in the dev resources folder
3. make update_source_data_prod: Only updates the endpoint resources (not NPPES information) stored in the prod resources directory
4.  make update_source_data: Updates the endpoint resources …
> NPPES Mapping Update

- docker-compose.override.yml
- docker-compose.yml
Added the cert directories to the docker compose file and removed them from the docker compose override file as they are not needed to be redefined in override file now that they are in the docker compose file.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 433 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-433) …
> Docker Compose Certs

- shinydashboard/Dockerfile
- shinydashboard/shiny-server.conf
Updated the shiny server version to the latest version, and disabled websockets in the shiny nginx configuration file to remove the websocket error that was being shown on staging.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 463 JIRA Ticket](https://oncprojectracking.healthit.gov/support/secure/RapidBoard.jspa?rapidView=55&projectKey=LANTERN&view=detail&selectedIssue=LANTERN-463)
- A …
> Staging Websocket Bug

- shinydashboard/lantern/about-lantern.html
- shinydashboard/lantern/aboutInfo.html
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/resourcemodule.R
- shinydashboard/lantern/modules/securitymodule.R
- shinydashboard/lantern/modules/smartresponsemodule.R
- shinydashboard/lantern/modules/validationsmodule.R
- shinydashboard/lantern/modules/valuesmodule.R
- shinydashboard/lantern/server.R
- shinydashboard/lantern/ui.R
Made some minor changes and fixes to the Lantern shiny dashboard UI such as:
- On the values page, made the selected number of entries shown in the table persist when you filter the table
- Turned off the multiselect on tables since it doesn't do anything
- Removed the footer on the "About Lantern" page, but kept the email
- Changed sentence on "About Lantern" page to make it more clear
- Added note on Validation page that the "messagingEndptRule" is not broken, it's an issue with the invariant itself
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 461 …
> Minor UI Updates

- Makefile
- scripts/history_prune_json_export.sh
Fixed the history_pruning and json_export makefile commands to run through docker so that they can run on staging without throwing an error due to the postgres container not having an exposed port to connect to.
**Submitter:** …
> history_pruning and json_export Makefile fix

- shinydashboard/lantern/disclaimer.html
- shinydashboard/lantern/modules/dashboardmodule.R
- shinydashboard/lantern/ui.R
Addressed the accessibility issues caught by the axe developer tool on the main dashboard page. One accessibility issue was not able to be fixed but I made a bug issue report on the shinydashboard github repo.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 468 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-468)
**Primary …
> Dashboard Accessibility

- shinydashboard/lantern/disclaimer.html
- shinydashboard/lantern/modules/dashboardmodule.R
- shinydashboard/lantern/ui.R
> Dashboard Accessibility (#282)

- shinydashboard/lantern/configuration.yml
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/global.R
- shinydashboard/lantern/modules/contactsmodule.R
- shinydashboard/lantern/server.R
- shinydashboard/lantern/ui.R
Added contact information page with contact data for each endpoint from their capability statements.
**Submitter:**
- Code is maintainable, …
> Contact info

- endpointmanager/pkg/chplendpointquerier/canvaswebscraper.go
- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/chplwebscraper.go
This PR added a web scraper to process the new endpoint list from CHPL. It also updated the old web scraper to fix an issue caused by a change to the site. 
**Submitter:** …
> Chpl canvas web scraper

- shinydashboard/lantern/functions/ui_functions.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/fieldsmodule.R
- shinydashboard/lantern/modules/implementationmodule.R
- shinydashboard/lantern/modules/resourcemodule.R
- shinydashboard/lantern/modules/valuesmodule.R
- shinydashboard/lantern/server.R
- shinydashboard/lantern/ui.R
Fixed accessibility issues from Endpoint tab to Values tab. I was not able to fix the accessibility issue on the fhir version drop down list that was caused by the dropdown button being given the wrong role, and some issues said needed to be manually reviewed so I looked at all of those and they seem fine but the accessibility warning cannot be removed.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 485 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-485)
- Tests have been run locally …
> Accessibility Fixes First Half

- shinydashboard/lantern/global.R
- shinydashboard/lantern/modules/capabilitystatementsizemodule.R
- shinydashboard/lantern/modules/dashboardmodule.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/fieldsmodule.R
- shinydashboard/lantern/modules/implementationmodule.R
- shinydashboard/lantern/modules/performancemodule.R
- shinydashboard/lantern/modules/validationsmodule.R
- shinydashboard/lantern/modules/valuesmodule.R
- shinydashboard/lantern/server.R
Fix all R linter errors on main branch caused by linter update.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 499 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-499)
- Edge cases have been checked to ensure …
> Fix all R linter errors

- shinydashboard/lantern/about-lantern.html
- shinydashboard/lantern/modules/capabilitystatementsizemodule.R
- shinydashboard/lantern/modules/contactsmodule.R
- shinydashboard/lantern/modules/downloadsmodule.R
- shinydashboard/lantern/modules/fieldsmodule.R
- shinydashboard/lantern/modules/locationmodule.R
- shinydashboard/lantern/modules/securitymodule.R
- shinydashboard/lantern/modules/smartresponsemodule.R
- shinydashboard/lantern/modules/validationsmodule.R
- shinydashboard/lantern/ui.R
Fixed the rest of the accessibility issues from the capability size tab to the about Lantern page. Some issues needed to be manually reviewed so I looked at all of those and they seem fine but the accessibility warning cannot be removed.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 486 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-486)
- A linter for the …
> Accessibility Second Half

- endpointmanager/pkg/chplendpointquerier/allscriptsquerier.go
- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/meditechwebscraper.go
This PR processes the Meditech endpoint list retrieved from CHPL
**Submitter:** …
> Processing meditech

- capabilityquerier/cmd/main.go
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/dashboardmodule.R
Made some small changes to the dashboard including:
- Removed the "Non Indexed Endpoints" info box
- Move Last Updated time to an info box, and rename it "Endpoints Last Queried"
- Fix up the info button text format and make it more detailed and easy to understand
- Fix vendor table NA problem
- Remove legend from HTTP response table
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 438 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-438)
- Code diff …
> Reevaluate dashboard

- endpointmanager/pkg/endpointmanager/postgresql/healthitproductstore_test.go
- endpointmanager/pkg/jsonexport/jsonexport.go
Added ORDER BY statement to the json export query so that the query always returns entries in order of descending updated_at times in order to fix a test that was relying on the entries being returned in that order. Also fixed a healthit_products_map test that was failing occasionally due to an entry that was being added with no index eventually reaching the index that the other two entries were added to the database with by making the index that the other two entries are added with a very high number.  
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 513 …
> Intermittent Test Fixes

- db/migration/migrations/000023_organization_location_view.down.sql
- db/migration/migrations/000023_organization_location_view.up.sql
- db/sql/dbsetup.sql
- shinydashboard/lantern/functions/db_connection.R
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/global.R
- shinydashboard/lantern/modules/dashboardmodule.R
- shinydashboard/lantern/modules/organizationsmodule.R
- shinydashboard/lantern/modules/smartresponsemodule.R
- shinydashboard/lantern/server.R
v2.0.0 was not working with current database of endpoints due to the endpoint export table being too large and causing the Lantern dashboard to time out since it had to be completely pulled into the dashboard before it would boot up. The endpoint export table has been made smaller by removing the organization location information and adding it to its own view, and the endpoint export table has been moved out of the R shiny global file so that the Lantern dashboard now will always boot up automatically and pull in the endpoint export table data when it is displaying the modal spinner. 
**Submitter:**
- …
> Production Timeout Fix

- endpointmanager/pkg/chplquerier/testdata/chpl_vendors.json
- endpointmanager/pkg/chplquerier/vendorquerier.go
- endpointmanager/pkg/chplquerier/vendorquerier_test.go
Replaced the usage of the 'developerId' field with 'id' for the CHPL /developers api endpoint and fixed test CHPL developers file to have this new format.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 526 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-526)
- Code has been run locally and the basic …
> CHPL Deprecated API developers -> developerId

- shinydashboard/lantern/modules/contactsmodule.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/organizationsmodule.R
- shinydashboard/lantern/modules/profilemodule.R
- shinydashboard/lantern/modules/securitymodule.R
- shinydashboard/lantern/modules/smartresponsemodule.R
- shinydashboard/lantern/modules/validationsmodule.R
- shinydashboard/lantern/server.R
- shinydashboard/lantern/ui.R
First priority accessibility changes including:
- Removing the tab-index for the body of the webpage so they aren't highlighted
- Distinct styling for hovering and focusing on elements
- Added a skip link to allow users to skip over the menu straight to the content
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 515 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-515)
- Code diff has been done and checked to ensure only expected code is being …
> Accessibility Priority Issues

- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/server.R
- Fixed issue with quotes and commas in the API Information Source Names that was causing the organizations listed in the details modal popup to not be on their own row. This was because some organizations were not surrounded in quotes and the function to split the organizations list relies on them all being surrounded by quotes. Now every organization is on its own row in the organization details popup. 
- Fixed organization detail popup modal to send the endpoint url as input so that the modal popup function can grab all organization names from a table using the endpoint url rather than trying to send all organization names through the shiny input which was …
> Endpoint Table Organization CSV Fix

- shinydashboard/lantern/server.R
- shinydashboard/lantern/ui.R
- Moved the "Select All" and "Deselect All" buttons outside of the FHIR version dropdown since it was not possible to tab to the buttons within the dropdown
- Changed colors of dropdowns and buttons to make them stand out more
- Change the aria labels of all of the dropdowns to better explain how to use and navigate them
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 518 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-518)
- Code diff has been done …
> Accessibility Dropdown Fixes

- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/contactsmodule.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/organizationsmodule.R
- shinydashboard/lantern/modules/profilemodule.R
- shinydashboard/lantern/modules/securitymodule.R
- shinydashboard/lantern/modules/smartresponsemodule.R
- shinydashboard/lantern/modules/validationsmodule.R
- shinydashboard/lantern/server.R
- shinydashboard/lantern/ui.R
Went through the Lantern dashboard with a screen reader and fixed issues including:
-  Added aria label to accordion boxes that say you need to click on them to expand
-  Added aria label to url links in endpoint tab table that say to click on them using Enter to open modal
-  Skip to content doesn’t work correctly pressing control option space, added aria-label that explains to press the enter key instead
-  Tabs don’t say you can click to switch tabs on Organizations page and Resource page, and tabs acted differently on profile tab and endpoint modal. Made all tabs look and act the same way, and added aria label to all of them that explains you can click on …
> Screen Reader Accessibility

- endpointmanager/pkg/chplendpointquerier/bundleparser.go
- endpointmanager/pkg/chplendpointquerier/cernerquerier.go
- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- resources/prod_resources/Altera_Digital_Health_Inc_EndpointSources.json
- resources/prod_resources/CHPLEndpointResourcesList.json
- resources/prod_resources/CHPLProductsInfo.json
- resources/prod_resources/Cerner_Corporation_EndpointSources.json
Created a CHPL Cerner list parser and updated the CHPL FHIR Bundle parser to work with the Cerner bundle so it's Organization information can be extracted.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 529 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-529)
- Code has been run locally and the basic …
> Update Cerner Lists

- shinydashboard/lantern/modules/contactsmodule.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/securitymodule.R
- shinydashboard/lantern/modules/smartresponsemodule.R
Fixed bug that was spotted when selecting "Naphcare, Inc" in the developer dropdown on the some of the Lantern tabs such as the Security, Contact, and SMART response pages. The issue was actually caused by the dropdown selection creating a resulting table with 0 rows, which was causing the code that creates the condensed endpoint list columns for the tables on these pages to crash. Added a check that makes sure the organization list is not completely empty before trying to split it and create the condensed organizations column.
**Submitter:**
- The JIRA ticket for …
> Fix Dropdown Napchare Errors 

- shinydashboard/lantern/modules/dashboardmodule.R
Added percentage column to the Endpoint Counts by Developer and FHIR Version table on dashboard page that shows the percentage of that developer's endpoints.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 543 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-543)
- Code has been run locally and the …
> Dashboard percentage column

- endpointmanager/pkg/endpointlinker/endpointlinker.go
- shinydashboard/lantern/modules/downloadsmodule.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/ui.R
Added the CSV download from the Endpoints page also on the Downloads page, and added a link on the Endpoints page under the CSV downloads that informs the user that they can also download endpoint data over time in the JSON format, as well as download the CSV file listed there on the Endpoints page, on the Downloads page as well by clicking on the link which will bring them to the Downloads page.
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 548 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-548)
- Tests are included and test …
> Lantern Downloads Update

- scripts/populatedb_prod.sh
Fixed the populatedb_prod script so that it deletes any NPPES files that should have been deleted from the resources directory the last time it was run to ensure that if the script ever crashes or is interrupted, running it again can clean up any files that should no longer be there. These files previously were causing issues if they still existed in the resources folder due to the script waiting for user input to allow overwriting the files, so now that they will always be deleted at the beginning of the script this should no longer be an issue. The production server also did not recognize some of the commands that were in the script, but changing the top of …
> Populatedb_prod NPPES Query Fix

- README.md
- scripts/automatic_populatedb_prod.sh
- scripts/history_prune_json_export.sh
Create script that calls the popualtedb_prod script that can be run automatically using cron, and update README with information on setting up this automatic production database population system
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 522 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-522)
- …
> Automate Populatedb Production

- shinydashboard/lantern/modules/dashboardmodule.R
Updated the fhir_vendor_table on the Lantern dashboard tab to be a paginated reactable, and updated the vendor_share_plot so that the x and y axes have been swapped and the table height has been increased
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 554 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-554)
**Primary …
> Fix Dashboard Table and Plot

- shinydashboard/lantern/functions/endpoints.R
Fixed query in dashboard that grabs products mapped to endpoint that was causing no products to show in the individual endpoint product matches table.
**Submitter:**
- Code is maintainable, reusable, efficient, and …
> Dashboard Product Mapping Fix

- db/migration/migrations/000026_add_list_source_info.down.sql
- db/migration/migrations/000026_add_list_source_info.up.sql
- db/sql/dbsetup.sql
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/server.R
Added a dropdown filter to the endpoint tab which allows the endpoint table to be filtered so that it shows either only endpoints from CHPL endpoint lists, only endpoints that are not from CHPL endpoint lists, or all endpoints. 
**Submitter:**
- The JIRA ticket for this PR is: [Lantern 555 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-555)
- A linter for the language has …
> Filter by CHPL

- endpointmanager/cmd/CHPLreport/main.go
Fixed CHPL report query so that the percentages are calculated with the full total of all the endpoints from 30 days rather than just the ones with a null capability statement or a non 200 http response.
**Submitter:** …
> Fix CHPL Report Query

- scripts/automatic_populatedb_prod.sh
- scripts/populatedb_prod.sh
- scripts/query-NPPES-resources.sh
> Fix NPPES Query Bugs

- shinydashboard/lantern/google-analytics.html
- shinydashboard/lantern/ui.R
> Add google analytics tags to shiny application

- .github/workflows/test.yml
> LANTERN-728: GitHub Actions Integration and End-to-end test run failures

- endpointmanager/pkg/jsonexport/jsonexport_integration_test.go
> LANTERN-726: Added a day check to handle the 31st of the month special case (Integration test bug)

- shinydashboard/lantern/functions/endpoints.R
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-586]
- Code follows style guidance …
> LANTERN-586: Fixing the error shown in values tab

- capabilityquerier/pkg/capabilityquerier/capabilityquerier.go
- db/migration/migrations/000028_remove_duplicates_healthit_products_map.down.sql
- db/migration/migrations/000028_remove_duplicates_healthit_products_map.up.sql
- db/sql/dbsetup.sql
- endpointmanager/pkg/endpointmanager/postgresql/healthitproductstore.go
**Submitter:**
- The JIRA ticket for this PR is: LANTERN-595, LANTERN-596
- Code follows style guidance …
> Lantern 595 remove duplicates healthit products map

- db/migration/migrations/000029_add_info_history_pruning_metadata.down.sql
- db/migration/migrations/000029_add_info_history_pruning_metadata.up.sql
> Lantern 729 migration script for history pruning algorithm

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/custombundlequerierparser.go
- endpointmanager/pkg/chplendpointquerier/healthsamuraiparser.go
> LANTERN-577, LANTERN-581: Modified HealthSamurai and Healthie webscrapers

- scripts/data_collection_check.sh
> LANTERN-590: Added logging for data collection check cron job

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/integraconnectwebscraper.go
- resources/dev_resources/CHPLEndpointResourcesList.json
- resources/prod_resources/CHPLEndpointResourcesList.json
… corresponding webscraper to use the bundle parser
**Submitter:**
- …
> LANTERN-580: Updated the Integra Connect URL webscraper

- scripts/automatic_endpoint_update.sh
> LANTERN-592: Added logging for the automatic endpoint update cron job

- capabilityquerier/pkg/capabilityquerier/capabilityquerier.go
- scripts/save_daily_csv_export.sh
> LANTERN-594: Logs for save_daily_csv_export.sh

- scripts/backup.sh
> LANTERN-591: Added logging for the backup cron job

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/emedpracticewebscraper.go
- endpointmanager/pkg/chplendpointquerier/humanaurlwebscraper.go
> LANTERN-579: Fixing lintr issues with eMed

- scripts/automatic_endpoint_update.sh
> LANTERN-731: Evaluate the endpoints belonging to the domain: fhir.fhirpoint.open.allscripts.com

- scripts/validations_cleanup.sh
> LANTERN-736: Update validation deletion implementation in validations cleanup script

- endpointmanager/pkg/endpointmanager/postgresql/historypruningstore.go
- endpointmanager/pkg/historypruning/historypruning.go
… data
**Submitter:**
- Code follows style guidance appropriate for …
> LANTERN-736: Update validation deletion implementation in history pruning algorithm

- endpointmanager/pkg/endpointmanager/postgresql/historypruningstore.go
> LANTERN-735: Reduce the history pruning query interval period

- NOTICE.md
- README.md
- shinydashboard/lantern/about-lantern.html
> LANTERN-732: Update ownership on ReadMe and About pages

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
> LANTERN-576: csvparser for saisystems

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/guidewellurlwebscraper.go
> LANTERN-627-Adding webscraper for Guidewell

- scripts/query-endpoint-resources.sh
> LANTERN-742: Implemented logging for the query-endpoint-resources.sh script

- shinydashboard/lantern/aboutInfo.html
> LANTERN-743: Added a new section in the About page to receive user feedback

- scripts/automatic_endpoint_update.sh
> LANTERN-753: Resolve Go version error returned by automatic endpoint update cron job

- endpointmanager/pkg/helpers/helpers.go
> LANTERN-766: Fixig version in user agent

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
> LANTERN-763: Adding bundle querier parsers

- db/migration/migrations/000030_add_indexes.down.sql
- db/migration/migrations/000030_add_indexes.up.sql
- db/sql/dbsetup.sql
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-759](https://oncprojectracking.healthit.gov/support/browse/LANTERN-759)
- Code …
> LANTERN-759: Created SQL indexes for optimizing the daily querying and history pruning Go routines

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
> LANTERN-756: Fixing varian webscraper

- endpointmanager/pkg/chplendpointquerier/bundleparser.go
- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
> Veradigm Missing Endpoints: Added a null check in BundleQuerierParser. Updated Veradigm source URL.

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/ehealthlinewebscraper.go
> LANTERN-769: ehealthline wenscraper

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/imedemrwebscraper.go
…aper to include the first row of the table.
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-783](https://oncprojectracking.healthit.gov/support/browse/LANTERN-783)
- Code is maintainable, …
> LANTERN-783: IMedEMR Webscraper

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/commomwebscrapers_test.go
- endpointmanager/pkg/chplendpointquerier/customcsvparser.go
- endpointmanager/pkg/chplendpointquerier/mdlandwebscraper.go
- endpointmanager/pkg/chplendpointquerier/netsmartparser.go
- endpointmanager/pkg/chplendpointquerier/ontadawebscraper.go
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-771](https://oncprojectracking.healthit.gov/support/browse/LANTERN-771), [LANTERN-772](https://oncprojectracking.healthit.gov/support/browse/LANTERN-772), [LANTERN-773](https://oncprojectracking.healthit.gov/support/browse/LANTERN-773)
- Code has been run locally and the basic functionality affected …
> LANTERN-771, LANTERN-772, LANTERN-773: Created new webscrapers for Ontada and MDLand. Create new CSV parsers. Modified the NetsmartCSVParser.

- endpointmanager/pkg/chplendpointquerier/betaAfoundriaWebScraper.go
- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
> LANTERN-770-BetaAfoundria-Webscraper

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/emdscloudwebscraper.go
> LLANTERN-788: Add-json-parser-emds

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/curemdwebscraper.go
> LANTERN-782-Add-curemd-webscraper

- .github/workflows/static.yml
- .github/workflows/test.yml
- endpointmanager/pkg/chplendpointquerier/aspmdewebscraper.go
- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/commomwebscrapers_test.go
- endpointmanager/pkg/chplendpointquerier/ezemrxwebscraper.go
- endpointmanager/pkg/chplendpointquerier/guidewellurlwebscraper.go
- endpointmanager/pkg/chplendpointquerier/guidewellurlwebscraper_test.go
- endpointmanager/pkg/chplendpointquerier/hcscwebscraper.go
- endpointmanager/pkg/chplendpointquerier/hcscwebscraper_test.go
- endpointmanager/pkg/chplendpointquerier/mdlandwebscraper.go
- endpointmanager/pkg/chplendpointquerier/ontadawebscraper.go
- Replaced macOS with ubuntu in static workflow file. 
- Specified OS and R versions in the workflow files. 
- Replaced fatal level logs with error value return statements. 
- Added error value-based conditional statements to the webscraper test files.
**Submitter:**
- Code has been run locally and the basic functionality …
> HOTFIX: Resolved Static Analysis and Tests failures in GitHub Actions

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
… file structure
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-796](https://oncprojectracking.healthit.gov/support/browse/LANTERN-796)
- Code is maintainable, reusable, efficient, and …
> LANTERN-796: Resolved the empty URL string issue for MEDENT_Community_Computer_Service_Inc_EndpointSources.json

- endpointmanager/pkg/chplendpointquerier/unitedhealthwebscraper.go
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-794](https://oncprojectracking.healthit.gov/support/browse/LANTERN-794)
- Code …
> LANTERN-794: Resolved the "Endpoints: null" contents of Medicare_UnitedHealthGroupEndpointSources.json

- endpointmanager/pkg/chplendpointquerier/unifywebscraper.go
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-795](https://oncprojectracking.healthit.gov/support/browse/LANTERN-795)
- Code …
> LANTERN-795: Resolved the "Endpoints: null" contents of TruBridge_Inc_EndpointSources.json

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
> LANTERN-797-Add-maximus-bundle-parser

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-800](https://oncprojectracking.healthit.gov/support/browse/LANTERN-800)
- Code …
> LANTERN-800: Updated the source endpoint URL for eClinical Works

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/commomwebscrapers_test.go
- endpointmanager/pkg/chplendpointquerier/zoobooksystemswebscraper.go
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-802](https://oncprojectracking.healthit.gov/support/browse/LANTERN-802)
- Code …
> LANTERN-802: Created a new webscraper and test file for Zoobook Systems

- scripts/automatic_populatedb_prod.sh
- scripts/populatedb.sh
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-801](https://oncprojectracking.healthit.gov/support/browse/LANTERN-801)
- Code …
> LANTERN-801: Created a log file for the populatedb script

- endpointmanager/pkg/chplendpointquerier/curemdwebscraper.go
> LANTERN-782: Trimming metadata suffix

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
- endpointmanager/pkg/chplendpointquerier/zoobooksystemswebscraper.go
> HOTFIX: Fixed the function return type of ZoobookSystemsWebscraper and resolved the lintr and test failures.

- docker-compose.yml
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-808](https://oncprojectracking.healthit.gov/support/browse/LANTERN-808)
- Code …
> LANTERN-808: Upgraded PostgreSQL version from 11.8 to 11.10

- scripts/automatic_populatedb_prod.sh
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-801](https://oncprojectracking.healthit.gov/support/browse/LANTERN-801)
- Code …
> LANTERN-801: Created a new directory to store populatedb script logs

- scripts/automatic_populatedb_prod.sh
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-785](https://oncprojectracking.healthit.gov/support/browse/LANTERN-785)
- Code …
> LANTERN-785: Disabled NPPES data download in automatic_populatedb_prod.sh

- scripts/query-endpoint-resources.sh
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-833](https://oncprojectracking.healthit.gov/support/browse/LANTERN-833)
- Code …
> LANTERN-833: Updated the CHPL API endpoint to fetch source endpoints of only Active Developers

- db/migration/migrations/000033_add_mv_resource_interactions.down.sql
- db/migration/migrations/000033_add_mv_resource_interactions.up.sql
- db/sql/dbsetup.sql
- scripts/refresh_materialized_views.sh
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/resourcemodule.R
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-832](https://oncprojectracking.healthit.gov/support/browse/LANTERN-832)
- Code …
> LANTERN-832: Created an SQL Materialized View for the Resources tab

- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/dashboardmodule.R
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-831](https://oncprojectracking.healthit.gov/support/browse/LANTERN-831)
- Code …
> HOTFIX - LANTERN-831: Reverted the get_http_response_summary_tbl function and created a new function to be used only for Dashboard Tab

- scripts/automatic_populatedb_prod.sh
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-785](https://oncprojectracking.healthit.gov/support/browse/LANTERN-785)
- Code …
> HOTFIX - LANTERN-785: Commented SHELL and PATH variables in automatic_populatedb_prod.sh to resolve Go error

- scripts/refresh_materialized_views.sh
> HOTFIX-LANTERN-835:Added a couple of column indexes to refresh script

- .github/workflows/static.yml
> HOTFIX: Changed workflow file to use an older version of golangci-lint since the new version has changed format.

- api/common/endpoints.R
- shinydashboard/lantern/functions/db_connection.R
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/global.R
- shinydashboard/lantern/modules/organizationsmodule.R
- shinydashboard/lantern/server.R
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-846](https://oncprojectracking.healthit.gov/support/browse/LANTERN-846)
- Code …
> LANTERN-846: Removed NPI organizations sub-tab and table connection to the front-end.

- db/migration/migrations/000038_add_organizationsmod_mv.down.sql
- db/migration/migrations/000038_add_organizationsmod_mv.up.sql
- db/sql/dbsetup.sql
- scripts/refresh_materialized_views.sh
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/organizationsmodule.R
- shinydashboard/lantern/server.R
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-839](https://oncprojectracking.healthit.gov/support/browse/LANTERN-839)
- Code …
> LANTERN-839: Organizations Tab Materialized View

- db/migration/migrations/000043_security_endpoints_mv.down.sql
- db/migration/migrations/000043_security_endpoints_mv.up.sql
- db/sql/dbsetup.sql
- scripts/refresh_materialized_views.sh
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/global.R
- shinydashboard/lantern/modules/securitymodule.R
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-844](https://oncprojectracking.healthit.gov/support/browse/LANTERN-844)
- Code …
> LANTERN-844: Security tab Materialized View

- api/common/endpoints.R
- db/migration/migrations/000051_add_endpoint_supported_profiles_mv.down.sql
- db/migration/migrations/000051_add_endpoint_supported_profiles_mv.up.sql
- db/sql/dbsetup.sql
- scripts/refresh_materialized_views.sh
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/global.R
- shinydashboard/lantern/modules/profilemodule.R
- shinydashboard/lantern/server.R
> Lantern 853 profiles tab mv

- endpointmanager/pkg/chplendpointquerier/chplendpointquerier.go
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-870](https://oncprojectracking.healthit.gov/support/browse/LANTERN-870)
- Code …
> HOTFIX LANTERN-870: Updated Greenway Health source endpoint URL and parser code

- scripts/vacuum.sh
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-739](https://oncprojectracking.healthit.gov/support/browse/LANTERN-739)
- Code …
> LANTERN-739: Created a vacuum.sh script to perform vacuum on Lantern database

- README.md
- db/README.MD
- endpointmanager/README.md
- shinydashboard/lantern/about-lantern.html
- shinydashboard/lantern/modules/capabilitystatementsizemodule.R
- shinydashboard/lantern/modules/dashboardmodule.R
- shinydashboard/lantern/modules/downloadsmodule.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/organizationsmodule.R
This update removes outdated references to NPPES data across the application and documentation:
•	Dashboard, Endpoints, CapStat Size, Downloads, and About tabs:
Removed all mentions of NPPES and related language (e.g., “discovered through the National Plan and Provider Enumeration System (NPPES)”).
•	README files:
•	Main README:
•	Removed general references to NPPES.
•	Retained only the mention of NPI files in dev_resources/, which are required by the populate_db script.
•	DB README:
•	Removed references to NPI organizations and NPPES-related tables that no longer exist.
•	EndpointManager README:
•	Removed references to the NPPES org populator and contact populator, as these packages are no longer used.
•	Retained mention of nppesquerier since it is still an active component.
Pull …
> HOTFIX: Remove outdated references to NPPES data on Lantern app

- shinydashboard/lantern/server.R
- Change filter to fhir_version instead of requested_fhir_version for endpoint
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-887](https://oncprojectracking.healthit.gov/support/browse/LANTERN-887) …
> HOTFIX: Fix organizations modal popup

- api/renv.lock
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/organizationsmodule.R
- shinydashboard/renv.lock
organizationsmodule.R:
•	Customized the group header for organization_name to remove the (n) count using a JavaScript grouped function.
•	Removed aggregation logic (aggregate = "count", colFormat) from the vendor_name column for a cleaner display.
renv update:
•	Upgraded reactable and its dependencies (including htmltools) to enable support for grouped column rendering.
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-886](https://oncprojectracking.healthit.gov/support/browse/LANTERN-886)
- Code …
> HOTFIX: Organizations tab: remove group count and "Total: X" labels

- shinydashboard/lantern/server.R
…now the first dev in the UI filter
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-890](https://oncprojectracking.healthit.gov/support/browse/LANTERN-890)
- Code is maintainable, reusable, …
> LANTERN-890: Removed the All Developers option in CapStat Size Tab UI filter

- db/migration/migrations/000060_update_mv_endpoint_totals_dashboard_count.down.sql
- db/migration/migrations/000060_update_mv_endpoint_totals_dashboard_count.up.sql
- db/sql/dbsetup.sql
…count discrepancy
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-893](https://oncprojectracking.healthit.gov/support/browse/LANTERN-893)
- Code is maintainable, reusable, efficient, and …
> LANTERN-893:  Fixed Endpoint Count Discrepancy on Dashboard Tab

- shinydashboard/lantern/functions/endpoints.R
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-892](https://oncprojectracking.healthit.gov/support/browse/LANTERN-892)
- Code …
> LANTERN-892: Added ordering in right static table of security tab

- db/sql/dbsetup.sql
> HOTFIX: Moved mv_endpoint_totals after selected_fhir_endpoints_mv

- shinydashboard/lantern/fhir_endpoint_organizations_fields.csv
- shinydashboard/lantern/modules/downloadsmodule.R
- shinydashboard/lantern/modules/organizationsmodule.R
- shinydashboard/lantern/server.R
> LANTERN-880-895: Created download buttons and new columns for the Organizations tab

- shinydashboard/lantern/modules/contactsmodule.R
- shinydashboard/lantern/server.R
> Lantern 911 contacts tab pagination

- shinydashboard/lantern/modules/smartresponsemodule.R
> added limit-offset pagination changes to smart response tab

- shinydashboard/lantern/server.R
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-916](https://oncprojectracking.healthit.gov/support/browse/LANTERN-916)
- Code …
> LANTERN-916: Removed All Developer option from Dropdown for fields, values, profiles tab

- shinydashboard/lantern/modules/contactsmodule.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/organizationsmodule.R
- shinydashboard/lantern/modules/profilemodule.R
- shinydashboard/lantern/modules/resourcemodule.R
- shinydashboard/lantern/modules/securitymodule.R
- shinydashboard/lantern/modules/smartresponsemodule.R
- shinydashboard/lantern/modules/valuesmodule.R
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-918](https://oncprojectracking.healthit.gov/support/browse/LANTERN-918)
- Code …
> LANTERN-918: Added double click protection on prev and next buttons for all tabs

- db/migration/migrations/000064_add_mv_profiles_paginated.down.sql
- db/migration/migrations/000064_add_mv_profiles_paginated.up.sql
- db/migration/migrations/000065_update_values_mv.down.sql
- db/migration/migrations/000065_update_values_mv.up.sql
- db/migration/migrations/000066_add_capstat_usage_summary_mv.down copy.sql
- db/migration/migrations/000066_add_capstat_usage_summary_mv.up.sql
- db/sql/dbsetup.sql
- scripts/refresh_materialized_views.sh
- shinydashboard/lantern/functions/endpoints.R
- shinydashboard/lantern/modules/contactsmodule.R
- shinydashboard/lantern/modules/endpointsmodule.R
- shinydashboard/lantern/modules/organizationsmodule.R
- shinydashboard/lantern/modules/profilemodule.R
- shinydashboard/lantern/modules/resourcemodule.R
- shinydashboard/lantern/modules/securitymodule.R
- shinydashboard/lantern/modules/smartresponsemodule.R
- shinydashboard/lantern/modules/validationsmodule.R
- shinydashboard/lantern/modules/valuesmodule.R
- shinydashboard/lantern/server.R
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-917](https://oncprojectracking.healthit.gov/support/browse/LANTERN-917)
- Code …
> LANTERN-917: Optimize Values Module for Performance

- db/migration/migrations/000067_add_security_endpoints_distinct_mv.down.sql
- db/migration/migrations/000067_add_security_endpoints_distinct_mv.up.sql
- db/sql/dbsetup.sql
- scripts/refresh_materialized_views.sh
- shinydashboard/lantern/modules/securitymodule.R
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-920](https://oncprojectracking.healthit.gov/support/browse/LANTERN-920)
- Code …
> LANTERN-920: Optimize performance of paginated security tab

- db/migration/migrations/000072_add_mv_organizations_final.down.sql
- db/migration/migrations/000072_add_mv_organizations_final.up.sql
- db/sql/dbsetup.sql
- scripts/refresh_materialized_views.sh
- shinydashboard/lantern/modules/organizationsmodule.R
**Submitter:**
- The JIRA ticket for this PR is: [LANTERN-973](https://oncprojectracking.healthit.gov/support/browse/LANTERN-973)
- Code …
> Added a new mv for grouping orgs with similar fields except endpoint url

- db/migration/migrations/000072_add_mv_organizations_final.up.sql
- db/sql/dbsetup.sql
> Fixed vendor parsing in the mv. Changed delimiter from , to ||||

- db/sql/dbsetup.sql
> Remove initialization of daily_querying_status
